### ISSUE TITLE
_auth_token not cleared on logout, is this intentional?

### ISSUE THREAD

**Issue by SamTrackbase** [masenf/reflex-local-auth#5]
The Local Storage object with key `_auth_token` is not deleted on logout. I would have thought it should be deleted - i.e. `self.auth_token = None` here? 

Thanks for a great package btw!

https://github.com/masenf/reflex-local-auth/blob/b51fef09a0a3634b7ec4f1c6b1e75e06c4827215/custom_components/reflex_local_auth/local_auth.py#L66

**Comment by masenf** [comment]
The auth_token has to be a str, but yeah, we could set it to "" after logout.

It's not a security issue because we deauth the session in the database, so the old token is no longer valid.

If you want to submit a PR, I'll take it.

**Comment by SamTrackbase** [comment]
Thanks - in local testing, setting this to "" doesn't seem to clear the value of _auth_token in the browser local storage (or not as far as I can tell) - but as you say not an issue really, so happy to close!
